server:
  port:
    ${PORT:12200}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    diskspace:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /springdoc/v3/api-docs
  swagger-ui:
    path: /springdoc/v3/swagger-ui.html
    deep-linking: true
    enabled: true
    disable-swagger-default-url: true
    url: /springdoc/v3/api-docs
    config-url: /springdoc/v3/api-docs/swagger-config
  default-flat-param-object: true

keycloak:
  ssl-required: external
  bearer-only: true
  truststore: ${trust-store}
  truststore-password: ${trust-store-password}
  config:
    file: keycloak.json
  realm: ${keycloak.realm}
  auth-server-url: ${keycloak.auth-server-url}
  resource: ${keycloak.resource}
  credentials:
    secret: ${keycloak.credentials.secret}

spring:
  profiles:
    default: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      platform: postgres
  task:
    scheduling:
      pool:
        size: 10
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/certs
  mail:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
          ssl:
            enable: true
  jpa:
    open-in-view: true
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: true
        jdbc:
          lab:
            non_contextual_creation: true
        event:
          entity_copy_observer: allow
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          ehcache:
            config: classpath:ehcache.xml
jwt:
  auth:
    converter:
      resource-id: ${keycloak.resource}
      principal-attribute: preferred_username

logging:
  level:
    org:
      keycloak: trace
      hibernate:
        sql: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
      springframework:
        security: trace
        web: trace
        data:
          jpa: trace