[versions]
kotlin = "1.9.10"
spring-boot = "3.1.3"
spring-boot-deps-management = "1.1.3"
kotlin-logging = "4.0.1"
assertk = "0.26.1"
ktlint = "11.5.1"
jakarta-api = "6.0.0"
jakarta-persistence = "3.1.0"
swagger = "1.7.0"
keycloak = "22.0.2"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
jakarta-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-api" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }

springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "swagger" }
springdoc-openapi-kotlin = { module = "org.springdoc:springdoc-openapi-kotlin", version.ref = "swagger" }
springdoc-openapi-data-rest = { module = "org.springdoc:springdoc-openapi-data-rest", version.ref = "swagger" }

keycloak-core = { module = "org.keycloak:keycloak-core", version.ref = "keycloak" }
keycloak-admin-client = { module = "org.keycloak:keycloak-admin-client", version.ref = "keycloak" }
keycloak-spring-boot = { module = "org.keycloak:keycloak-spring-boot-starter", version.ref = "keycloak" }

postgresql = { module = "org.postgresql:postgresql"}
jandex = { module = "org.jboss:jandex", version.ref = "spring-boot"}
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-elasticsearch = { module = "org.springframework.boot:spring-boot-starter-data-elasticsearch" }
spring-boot-starter-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat" }
spring-boot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }

#Tests
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-deps = { id = "io.spring.dependency-management", version.ref = "spring-boot-deps-management" }