name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Gradlew Build
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=build/libs/*.jar -t app .

      - name: Save Docker image as tar
        run:  docker save -o app.tar app

      - name: Transfer files to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./app.tar
          target: /home/project/backend

      - name: SSH into remote server and run Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/backend
            docker container stop backend
            docker container rm backend
            docker rmi app
            docker load -i app.tar
            docker run -d -p 12200:12200 --env-file env.txt --log-opt max-size=50m --name backend app
