name: deploy

on:
  push:
    branches:
      - main
      
env:
  GITHUB_USERNAME: ${{ secrets.USERNAME }}
  GITHUB_TOKEN: ${{ secrets.SSH_TOKEN }}
  SSHK: ${{ secrets.SUBMODULE_CONTENT_PULL_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.SSH_TOKEN }}
      - name: Trigger release build
        run: |
            mkdir -p $HOME/.ssh
            echo "$SSHK" > $HOME/.ssh/ssh.key
            chmod 600 $HOME/.ssh/ssh.key
            export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
            git submodule update --init --recursive

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Gradlew Build
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=build/libs/*.jar -t app .

      - name: Save Docker image as tar
        run:  docker save -o app.tar app

      - name: Transfer files to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./app.tar
          target: /home/project/backend

      - name: SSH into remote server and run Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/project/backend
            docker container stop backend
            docker container rm backend
            docker rmi app
            docker load -i app.tar
            docker run -d -p 12200:12200 --env-file env.txt --log-opt max-size=50m --name backend app
